server:
  port: 8082

spring:
  application:
    name: validationCNPJ
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group
  amqp:
    deserialization:
      trust:
        all: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        message-converter:
          trusted-packages: com.seuprojeto.common.consumer.dto.MessageWrapper

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

messaging:
  type: kafka
  rabbit:
    exchange: minhaexchange