server:
  port: 8082

spring:
  application:
    name: validationCNPJ
  profiles:
    active: kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: meu-grupo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full